// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwdB2mLtUG3kKgcM0yCkKIkeHVsIEunQU',
    appId: '1:981999352204:web:8517c89d9e34b050bffea9',
    messagingSenderId: '981999352204',
    projectId: 'flutter-tes-firebase',
    authDomain: 'flutter-tes-firebase.firebaseapp.com',
    storageBucket: 'flutter-tes-firebase.appspot.com',
    measurementId: 'G-Q6FYTTZRCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTn8-xBgNfuU88Kx7FSvIKfarWH4wrJjs',
    appId: '1:981999352204:android:10e1540708232d63bffea9',
    messagingSenderId: '981999352204',
    projectId: 'flutter-tes-firebase',
    storageBucket: 'flutter-tes-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH40dt7Psza3D7T4u9oqw73KmDHEdPva8',
    appId: '1:981999352204:ios:7073b63b311e3a61bffea9',
    messagingSenderId: '981999352204',
    projectId: 'flutter-tes-firebase',
    storageBucket: 'flutter-tes-firebase.appspot.com',
    iosClientId: '981999352204-v6a2asqeidvnd7egh7vsc683mq1iqidf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH40dt7Psza3D7T4u9oqw73KmDHEdPva8',
    appId: '1:981999352204:ios:7073b63b311e3a61bffea9',
    messagingSenderId: '981999352204',
    projectId: 'flutter-tes-firebase',
    storageBucket: 'flutter-tes-firebase.appspot.com',
    iosClientId: '981999352204-v6a2asqeidvnd7egh7vsc683mq1iqidf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesFirebase',
  );
}
